# Book settings
title: ds4p
author: Corrado Caudek
logo: "images/logo.png"
copyright: "2024"

execute:
  execute_notebooks: cache

latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references/references.bib

bibtex_reference_style:
  - author_year

repository:
  url: https://github.com/ccaudek/ds4p
  path_to_book: docs/
  branch: main

footer_text: Created by <a href="https://ccaudek.github.io/caudeklab/">Corrado Caudek</a> using <a href="https://jupyterbook.org/">Jupyter Book</a>.

launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""
  thebe: false

html:
  theme:
    name: sphinx_book_theme
    options:
      description: "Dispense di Psicometria, Scienze e Tecniche Psicologiche, UniFi"
      fixed_sidebar: true
      navigation_with_keys: true
  favicon: "images/increasing.png"
  google_analytics_id: "G-TP2WLBPMS6"
  baseurl: "https://ccaudek.github.io/ds4p"
  use_repository_button: false
  use_edit_page_button: false
  use_issues_button: false
  comments:
    hypothesis: false

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
  config:
    language: it
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_enable_extensions:
      - amsmath
      - dollarmath
    numfig: true
    numfig_secnum_depth: 2 # Numero di livelli di profondità della numerazione delle sezioni (2 include sezioni e sottosezioni)

exclude_patterns:
  - "sandbox/*"

# Abilita la numerazione delle sezioni e sottosezioni
numbered: true
